Map<String, String> skillConst = {
  "0": "Unknown Skill",
  "1": "Normal Skill",
  "2": "High Skill",
  "3": "Very High Skill",
};

Map<String, String> lobbyConst = {
  "0": "Normal",
  "1": "Practice",
  "2": "Tournament",
  "3": "Tutorial",
  "4": "Co-Op Bots",
  "5": "Ranked Team MM (Legacy)",
  "6": "Ranked Solo MM (Legacy)",
  "7": "Ranked",
  "8": "1v1 Mid",
  "9": "Battle Cup",
};
Map<String, String> modeConst = {
  "0": "Unknown",
  "1": "All Pick",
  "2": "Captains Mode",
  "3": "Random Draft",
  "4": "Single Draft",
  "5": "All Random",
  "6": "Intro",
  "7": "Diretide",
  "8": "Reverse Captains Mode",
  "9": "The Greeviling",
  "10": "Tutorial",
  "11": "Mid Only",
  "12": "Least Played",
  "13": "Limited Heroes",
  "14": "Compendium",
  "15": "Custom",
  "16": "Captains Draft",
  "17": "Balanced Draft",
  "18": "Ability Draft",
  "19": "Event",
  "20": "All Random Deathmatch",
  "21": "1v1 Solo Mid",
  "22": "All Draft",
  "23": "Turbo",
  "24": "Mutation",
};

Map<String, String> regionConst = {
  "0": "Automatic",
  "1": "US West",
  "2": "US East",
  "3": "Luxembourg",
  "5": "Singapore",
  "6": "Dubai",
  "7": "Australia",
  "8": "Stockholm",
  "9": "Austria",
  "10": "Brazil",
  "11": "South Africa",
  "12": "China TC Shanghai",
  "13": "China UC",
  "14": "Chile",
  "15": "Peru",
  "16": "India",
  "17": "China TC Guangdong",
  "18": "China TC Zhejiang",
  "19": "Japan",
  "20": "China TC Wuhan",
  "25": "China UC 2",
};
